name: CI
on:
  push:
    paths:
      - '.github/**'
      - 'packages/**'
      - 'package.json'
      - 'yarn.lock'
      - '!demo/**'
      - '!docs/**'
      - '!**.md'
      - '!.changeset/**'
jobs:
  build:
    name: Build, lint, and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> "$GITHUB_OUTPUT"

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --silent

      - name: Check types
        run: yarn tsc

      - name: Check formatting
        run: yarn prettier

      - name: Lint files
        run: yarn lint:full

      - name: Cache Yarn build output
        uses: actions/cache@v3
        id: yarn-build-cache
        with:
          path: packages/**/dist
          key: ${{ runner.os }}-yarn-build-${{ hashFiles('packages/') }}
          restore-keys: |
            ${{ runner.os }}-yarn-build-

      - name: Yarn build (if no cache hit)
        if: steps.yarn-build-cache.outputs.cache-hit != 'true'
        run: yarn build

      - name: Cypress run
        run: yarn ci:test
